### ISSUE TITLE
CUH-1215A Not enough system memory 

### ISSUE THREAD

**Issue by mex20** [valentinbreiz/PS4-Linux-Loader#12]
When I send the 4.55 payload, I get the "There is not enough system memory" error. I am on 4.55 firmware and other payloads seem to work just fine. I am even using eely's bzimage from March 25. I am using the "original" exploit from the ps4-exploit-host for 4.55. If I choose the FTP exploit, and then run the original exploit, the error does not occur. However Linux doesnt appear to try to load. The ps4 just stays on the "You're all set!" screen.

**Comment by ghost** [comment]
I have the same problem with the PS4 having a panic and shutting down after sending the payload, it seems as though the screen goes black as though its going to start to load Linux and maybe go to a rescue shell but it turns out the model (CUH-1215A) I am trying to install Linux to isn't supported currently by the payload

CUH-1115B working
CUH-1102A working 
CUH-1115A working 
CUH-1116A working
CUH-1004A working
CUH-1001A working
CUH-1116B working



CUH-1215A not working
CUH-1216A not working 
CUH-1208B not working 
CUH-1216 not working 
CUH-1216B not working 
CUH-2015A not working
CUH-1008A not working
CUH-7016B not working
CUH-7015B not working
CUH-2016B not working




please see here
https://twitter.com/valentinbreiz/status/947864073085079552?lang=en

**Comment by valentinbreiz** [comment]
This tweet is old now these models are supported thanks to eeply's work

**Comment by ghost** [comment]
@mex20,
I just recompiled a 5.05 Linux Loader based on this code, but for 720p
because I was just experiencing the same problem in the last few days trying to load Fedora,

^ this is for the Linux Loader for 5.05 in 720p for CUH-1215A models, probably most CUH-12XX models,
you have to switch your PS4 video resolution from 1080p to 720p
its working for me, using the same initrd and bzImage for 5.05


PS4-Linux-Loader-5.05.720p.bin	
https://mega.nz/#!P3wEWCLL!fGI_LSwbNo7qwW7X_didKKs59XTp_6qkVnkF79eSIzo

bzImage and initrd

5.05-fat32-files-for-720p-1080p-loader.zip
https://mega.nz/#!Sixg1aBD!HDtq6qDA8NR-Ta3Rpukt1mB6GNx-euTQnXUipG3YH70

**Comment by mirh** [comment]
CUH-2116B on 5.07 doesn't work with that either...

**Comment by ghost** [comment]
The payload is recompiled specifically for 5.05 I could try to update to 5.07 in a week or so to test, been busy packaging something

**Comment by ghost** [comment]
@mirh 
also there is no current Payload here for 5.07 can you explain how you attempt to load linux on 5.07 ?

**Comment by ghost** [comment]
this current recompiled 5.05 payload doesn't show the init screen, because of a slight error, in the resolution, if the screen changes to a black and white speckled pattern like a TV on an out of bound channel with no reception, to switch ttys hit "crtl-alt-F1", "crtl-alt-F2" to enter the login screen

**Comment by mirh** [comment]
I attempt to load 5.07 from ps4-exploit-host web page. 
~~If (for as much they are similar) 5.05 doesn't work on 5.07.. could I help in any way?~~

~~EDIT: I'm told people had no problems with it. So I still stand for this issue~~
EDIT2: well, it now works. Oddly, ps4-host-exploit original sender was bugged till today

**Comment by chapas** [comment]
Having the same problem, on 5.05, CUH-1003A, "Not enough system memory".

**Comment by ghost** [comment]
@chapas
"Not enough system memory". with MIRAHEN that's a common bug in how the web kit exploit loads,

**Comment by chapas** [comment]
Ok,
Still I have never seen this error with the other payloads. 
Also with Linux loader, it stays forever spinning without anything happening. 
Already tried 2 different usb devices and no luck. Where can I check Linux loader log/debug information?

**Comment by ghost** [comment]
the first message should say "All set, or You are all set!"
you exit the WWW browser
load MIRAHEN again
it should say "Waiting for Payload"
then you send the payload to the ps4's ip address my PS4 uses 10.0.5.25 as an ip address
so from a terminal with netcat you bit bang the payload to the PS4 through your LAN on the PS4
#root:10.0.5.2#      nc 10.0.5.25 9020 < PS4-Linux-Loader-5.05.720p.bin

where this is the command to execute in the directory containing PS4-Linux-Loader-5.05.x.bin
nc 10.0.5.25 9020 < PS4-Linux-Loader-5.05.720p.bin

**Comment by chapas** [comment]
After much keyb. bagging, i have successfully run Manjaro distro. on PS4, follow the instructions from BataBo: https://forum.darksoftware.net/threads/ps4-phat-slim-pro-linux-loader-5-05-manjaro-linux-ps4-v2.837/page-3

This loader is working for me.

**Comment by kadyes1** [comment]
does 2116b works or still

**Comment by mex20** [comment]
@valentinbreiz I am still unable to get beyond this error on my CUH-1215A ps4 on 4.55 firmware. No matter what tools or methods I use, I still get the same error. Do you have any suggestions for how to solve the issue on this hardware?

**Comment by sniper1973** [comment]
fonctionne pas sur 2116b

**Comment by mex20** [comment]
This issue isn't solved for my CUH-1215A console, but because no one besides you @valentinbreiz knows how to read, I'm closing this so that they don't keep "contributing" that is not related to this issue. 

The guide that was posted and "tutorial" do not specifically say what hardware model they are for, and therefore are useless to this discussion.
